# Centralize repository-wide Go rewrites and verification behind one deterministic command.
.PHONY: check
check:
	goimports -w .
	go fix ./...
	go vet ./...
	gopls check
	staticcheck ./...
	go test -race ./...
	golangci-lint run ./...
	find . -type f -name '*.sh' -not -path './.git/*' -exec shellcheck {} +
